INSERT INTO `categorie`
VALUES (1, "Circulation / Exploitation (EX)", NULL), (2, "Documentaliste (3DOCU)", 1), (3, "Expert métier Sécurité(5ESEC)", 1), (4, "Formateur / Formatrice (4FORM)", 1), (5, "Gestionnaire / Concepteur / Conceptrice sillons (4GSIL)", 1), (6, "Gestionnaire PC (4GEPC)", 1), (7, "Manager de proximité circulation / exploitation (5DPXX)", 1), (8, "Opérateur ferroviaire circulation (2OFCI)", 1), (9, "Référent Technique Qualité Sécurité(4RTQS)", 1), (10, "Responsable de PC (5DUPC)", 1), (11, "Responsable d'unité Circulation / exploitation (7DUOC)", 1), (12, "Responsable HQSE (5HQSE)", 1), (13, "Responsable pôle de sécurité ferroviaire (6RPSF)", 1), (14, "Technicien ferroviaire circulation (4TCEX)", 1), (15, "Conduite / Manoeuvre Matériel voyageur et fret (TR)", NULL), (16, "Conducteur de tram-train (3CRTT)", 15), (17, "Conducteur ligne (4CRLG)", 15), (18, "Conducteur manoeuvre, remonte et navette fret (3CRML)", 15), (19, "Expert métier Sécurité(5ESEC)", 15), (20, "Formateur / Formatrice (4FORM)", 15), (21, "Gestionnaire moyens humains / matériels (4RESS)", 15), (22, "Manager de proximité Conduite (5DPXT)", 15), (23, "Référent Technique Qualité Sécurité(4RTQS)", 15), (24, "Responsable conception et / ou méthode (6RCME)", 15), (25, "Responsable pôle de sécurité ferroviaire (6RPSF)", 15), (26, "Fonctions transverses (FT)", NULL), (27, "Chargé de gestion ressource / support (4CGRS)", 26), (28, "Chargé de gestion ressources financières (4CGFI)", 26), (29, "Chargé de gestion Ressources Humaines (4CGRH)", 26), (30, "Gestionnaire ressource / support (2GERS)", 26), (31, "Gestionnaire Ressources Financières (2GERF)", 26), (32, "Gestionnaire Ressources Humaines (2GERH)", 26), (33, "Opérateur de l'environnement de travail (2OPET)", 26), (34, "Responsable de Production formation (7DUPF)", 26), (35, "Responsable ressource / support (7RRSU)", 26), (36, "Responsable ressources financières (7REFI)", 26), (37, "Responsable ressources humaines (7RERH)", 26), (38, "Spécialiste ressource / support (5SPRS)", 26), (39, "Spécialiste ressources financières (5SPFI)", 26), (40, "Spécialiste ressources humaines (5SPRH)", 26), (41, "Gestion foncière et immobilière (IM)", NULL), (42, "Manager de proximité Travaux Patrimoine (5DPXG)", 41), (43, "Opérateur / Opératrice Patrimoine (2OPGA)", 41), (44, "Responsable Affaires Immobilières (6RAFI)", 41), (45, "Responsable d'activité Patrimoine (6RAPA)", 41), (46, "Spécialiste Maintenance Immobilières Services (5SMIS)", 41), (47, "Spécialiste Méthode Patrimoine (5SMEP)", 41), (48, "Technicien (ne) Gestion Immobilière Locative (4TCIM)", 41), (49, "Technicien / Technicienne Patrimoine (4TCPA)", 41), (50, "Maintenance Ingénierie et travaux du réseau (MT)", NULL), (51, "Appui aux Projets (4APUI)", 50), (52, "Chargé de production ingénierie (5CHPI)", 50), (53, "Chef de projet MOE (6CPMO)", 50), (54, "Documentaliste (3DOCU)", 50), (55, "Expert métier Sécurité(5ESEC)", 50), (56, "Formateur / Formatrice (4FORM)", 50), (57, "Manager proximité maintenance travaux infra (5DPXV)", 50), (58, "Opérateur fabrication maintenance industrie (2OFMI)", 50), (59, "Opérateur maintenance travaux infrastructure (2OMTI)", 50), (60, "Opérateur maintenance travaux syst élec (2OMTS)", 50), (61, "Opérateur maintenance travaux telecoms (2OMTT)", 50), (62, "Référent Technique Qualité Sécurité(4RTQS)", 50), (63, "Régulateur sous stations (4RSST)", 50), (64, "Responsable Activité Maintenance Tx Infra (7RMTI)", 50), (65, "Responsable d'Equipe Maintenance et Travaux (4REMT)", 50), (66, "Responsable HQSE (5HQSE)", 50), (67, "Responsable ingénierie (7RING)", 50), (68, "Responsable MOA / Pilote d'opération (6RMOA)", 50), (69, "Responsable pôle de sécurité ferroviaire (6RPSF)", 50), (70, "Spécialiste Méthode Planif Maintenance Tx (5SMTX)", 50), (71, "Technicien M&T de l'infrastructure (4TCMT)", 50), (72, "Technicien M&T des systèmes télécoms (4TCTE)", 50), (73, "Technicien M&T systèmes électriques (4TCSE)", 50), (74, "Maintenance matériel roulant et spécialisée (MA)", NULL), (75, "Expert métier Sécurité(5ESEC)", 74), (76, "Formateur / Formatrice (4FORM)", 74), (77, "Ingénieur maintenance orga industrielle (6IMOI)", 74), (78, "Manager de proximité Matériel (5DPXM)", 74), (79, "Opérateur (rice) de maintenance industrielle (2OMIN)", 74), (80, "Opérateur (rice) maintenance matériels (2OMAT)", 74), (81, "Référent Technique Qualité Sécurité(4RTQS)", 74), (82, "Responsable Activité Maint Matériel Roulant (7RMAT)", 74), (83, "Responsable HQSE (5HQSE)", 74), (84, "Responsable pôle de sécurité ferroviaire (6RPSF)", 74), (85, "Technicien gestion maint ing orga indus (4TCOR)", 74), (86, "Technicien (ne) maintenance des Matériels (4TCMA)", 74), (87, "Médical / social (ME)", NULL), (88, "Responsable Médical / Social (6RMED)", 87), (89, "Technicien / Technicienne Paramédical (4TCME)", 87), (90, "Technicien / Technicienne social et familial (4TCSF)", 87), (91, "Pilotage et animation de sécurité et qualité(QS)", NULL), (92, "Documentaliste (3DOCU)", 91), (93, "Expert métier Sécurité(5ESEC)", 91), (94, "Formateur / Formatrice (4FORM)", 91), (95, "Référent Technique Qualité Sécurité(4RTQS)", 91), (96, "Responsable HQSE (5HQSE)", 91), (97, "Responsable pôle de sécurité ferroviaire (6RPSF)", 91), (98, "Production ferroviaire (PF)", NULL), (99, "Chef d'Escale (4CDES)", 98), (100, "Expert métier Sécurité(5ESEC)", 98), (101, "Formateur / Formatrice (4FORM)", 98), (102, "Gestionnaire moyens humains / matériels (4RESS)", 98), (103, "Manager de Proximité Fret (5DPXF)", 98), (104, "Manager de Proximité Production (5DPXP)", 98), (105, "Manutentionnaire (1MANU)", 98), (106, "Opérateur de production et de sécurité au sol (2OPSS)", 98), (107, "Opérateur ferroviaire industrie (2OFIN)", 98), (108, "Opérateur Fret au sol (2OPFR)", 98), (109, "Référent Technique Qualité Sécurité(4RTQS)", 98), (110, "Responsable conception et / ou méthode (6RCME)", 98), (111, "Responsable HQSE (5HQSE)", 98), (112, "Spécialiste gestion de production fret (6SGPF)", 98), (113, "Technicien Fret (4TFFR)", 98), (114, "Responsables / Management (MG)", NULL), (115, "Directeur commercial (8DICO)", 114), (116, "Directeur ressource / support (8DIRS)", 114), (117, "Directeur / responsable d'activité ferroviaire (8DIFE)", 114), (118, "Responsable d'unité voyageurs transverse (6RUVT)", 114), (119, "Responsable Périmètre Fret (7RFRE)", 114), (120, "Services / Relation Client / Marketing (RC)", NULL), (121, "Agent accompagnement train / relation client (2AARC)", 120), (122, "Assistant (e) commercial (le) opérationnel (le)(3ASCO)", 120), (123, "Chargé de gestion de site (2CGSI)", 120), (124, "Chargé de la relation client (2CHRC)", 120), (125, "Chargé(e) d'affaires commercial marketing (5CACM)", 120), (126, "Chef d'équipe Relation Client (4CERC)", 120), (127, "Expert métier Sécurité(5ESEC)", 120), (128, "Formateur / Formatrice (4FORM)", 120), (129, "Manager de proximité Relation client (5DPXC)", 120), (130, "Référent Technique Qualité Sécurité(4RTQS)", 120), (131, "Responsable commercial et marketing (6RCMK)", 120), (132, "Spécialiste commercial et marketing Fret (6SCMF)", 120), (133, "Technicien Commercial Fret (4TCFR)", 120), (134, "Technicien / Technicienne Commercial (e)(4TCCO)", 120), (135, "Sureté(SG)", NULL), (136, "Formateur / Formatrice (4FORM)", 135), (137, "Manager Sûreté Ferroviaire (5MGSG)", 135), (138, "Opérateur de la sûreté ferroviaire (2OPSG)", 135), (139, "Responsable Sûreté Ferroviaire (6RESG)", 135), (140, "Spécialiste Sûreté ferroviaire (5SPSG)", 135), (141, "Technicien Sûreté ferroviaire (4TSFE)", 135), (142, "Système d'information et digital (SI)", NULL), (143, "Architecte et Urbaniste des SI (6ARSI)", 142), (144, "Concepteur (rice)/Développeur (se)(4DEVL)", 142), (145, "Responsable Informatique et Digital (6RIDI)", 142), (146, "Spécialiste Informatique et Digital (5SIDI)", 142), (147, "Technicien (ne) Informatique et Digital (4TCGI)", 142);
INSERT INTO `role`
VALUES (1, 'Innovateur', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    (2, 'Manager', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    (3, 'Ambassadeur', 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0),
    (4, 'Administrateur', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO `organisation`
VALUES (1, 'Auvergne-Rhône-Alpes'),
    (2, 'Bourgogne-Franche-Comté'),
    (3, 'Bretagne'),
    (4, 'Centre-Val de Loire'),
    (5, 'Corse'),
    (6, 'Grand Est'),
    (7, 'Hauts-de-France'),
    (8, 'Île-de-France'),
    (9, 'Normandie'),
    (10, 'Nouvelle-Aquitaine'),
    (11, 'Occitanie'),
    (12, 'Pays de la Loire'),
    (13, "Provence-Alpes-Côte d'Azur");
INSERT INTO `team`
VALUES (1, 'Resources Humaines', 1),
    (2, 'Equipe production Ouest', 1),
    (3, 'Equipe relation client', 1),
    (4, 'Equipe production télécom', 1),
    (5, 'Equipe production voie', 1),
    (6, 'Equipe production caténaire', 1),
    (7, 'Equipe production signalisation', 1),
    (8, 'Resources Humaines', 2),
    (9, 'Equipe production Ouest', 2),
    (10, 'Equipe relation client', 2),
    (11, 'Equipe production télécom', 2),
    (12, 'Equipe production voie', 2),
    (13, 'Equipe production caténaire', 2),
    (14, 'Equipe production signalisation', 2),
    (15, 'Resources Humaines', 3),
    (16, 'Equipe production Ouest', 3),
    (17, 'Equipe relation client', 3),
    (18, 'Equipe production télécom', 3),
    (19, 'Equipe production voie', 3),
    (20, 'Equipe production caténaire', 3),
    (21, 'Equipe production signalisation', 3),
    (22, 'Resources Humaines', 4),
    (23, 'Equipe production Ouest', 4),
    (24, 'Equipe relation client', 4),
    (25, 'Equipe production télécom', 1),
    (26, 'Equipe production voie', 4),
    (27, 'Equipe production caténaire', 4),
    (28, 'Equipe production signalisation', 4),
    (29, 'Resources Humaines', 5),
    (30, 'Equipe production Ouest', 5),
    (31, 'Equipe relation client', 5),
    (32, 'Equipe production télécom', 5),
    (33, 'Equipe production voie', 5),
    (34, 'Equipe production caténaire', 5),
    (35, 'Equipe production signalisation', 5),
    (36, 'Resources Humaines', 6),
    (37, 'Equipe production Ouest', 6),
    (38, 'Equipe relation client', 6),
    (39, 'Equipe production télécom', 6),
    (40, 'Equipe production voie', 6),
    (41, 'Equipe production caténaire', 6),
    (42, 'Equipe production signalisation', 6),
    (43, 'Resources Humaines', 7),
    (44, 'Equipe production Ouest', 7),
    (45, 'Equipe relation client', 7),
    (46, 'Equipe production télécom', 7),
    (47, 'Equipe production voie', 7),
    (48, 'Equipe production caténaire', 7),
    (49, 'Equipe production signalisation', 7),
    (50, 'Resources Humaines', 8),
    (51, 'Equipe production Ouest', 8),
    (52, 'Equipe relation client', 8),
    (53, 'Equipe production télécom', 8),
    (54, 'Equipe production voie', 8),
    (55, 'Equipe production caténaire', 8),
    (56, 'Equipe production signalisation', 8),
    (57, 'Resources Humaines', 9),
    (58, 'Equipe production Ouest', 9),
    (59, 'Equipe relation client', 9),
    (60, 'Equipe production télécom', 9),
    (61, 'Equipe production voie', 9),
    (62, 'Equipe production caténaire', 9),
    (63, 'Equipe production signalisation', 9),
    (64, 'Resources Humaines', 10),
    (65, 'Equipe production Ouest', 10),
    (66, 'Equipe relation client', 10),
    (67, 'Equipe production télécom', 10),
    (68, 'Equipe production voie', 10),
    (69, 'Equipe production caténaire', 10),
    (70, 'Equipe production signalisation', 10),
    (71, 'Resources Humaines', 11),
    (72, 'Equipe production Ouest', 11),
    (73, 'Equipe relation client', 11),
    (74, 'Equipe production télécom', 11),
    (75, 'Equipe production voie', 11),
    (76, 'Equipe production caténaire', 11),
    (77, 'Equipe production signalisation', 11),
    (78, 'Resources Humaines', 12),
    (79, 'Equipe production Ouest', 12),
    (80, 'Equipe relation client', 12),
    (81, 'Equipe production télécom', 12),
    (82, 'Equipe production voie', 12),
    (83, 'Equipe production caténaire', 12),
    (84, 'Equipe production signalisation', 12),
    (85, 'Resources Humaines', 13),
    (86, 'Equipe production Ouest', 13),
    (87, 'Equipe relation client', 13),
    (88, 'Equipe production télécom', 13),
    (89, 'Equipe production voie', 13),
    (90, 'Equipe production caténaire', 13),
    (91, 'Equipe production signalisation', 13);
