INSERT INTO `categorie`
VALUES (1, "Circulation / Exploitation(EX)", NULL), (2, "Documentaliste(3DOCU)", 1), (3, "Expert métier Sécurité(5ESEC)", 1), (4, "Formateur/Formatrice(4FORM)", 1), (5, "Gestionnaire / Concepteur/Conceptrice sillons(4GSIL)", 1), (6, "Gestionnaire PC(4GEPC)", 1), (7, "Manager de proximité circulation/exploitation(5DPXX)", 1), (8, "Opérateur ferroviaire circulation(2OFCI)", 1), (9, "Référent Technique Qualité Sécurité(4RTQS)", 1), (10, "Responsable de PC(5DUPC)", 1), (11, "Responsable d'unité Circulation/exploitation(7DUOC)", 1), (12, "Responsable HQSE(5HQSE)", 1), (13, "Responsable pôle de sécurité ferroviaire(6RPSF)", 1), (14, "Technicien ferroviaire circulation(4TCEX)", 1), (15, "Conduite/Manoeuvre Matériel voyageur et fret(TR)", NULL), (16, "Conducteur de tram-train(3CRTT)", 15), (17, "Conducteur ligne(4CRLG)", 15), (18, "Conducteur manoeuvre, remonte et navette fret(3CRML)", 15), (19, "Expert métier Sécurité(5ESEC)", 15), (20, "Formateur/Formatrice(4FORM)", 15), (21, "Gestionnaire moyens humains/matériels(4RESS)", 15), (22, "Manager de proximité Conduite(5DPXT)", 15), (23, "Référent Technique Qualité Sécurité(4RTQS)", 15), (24, "Responsable conception et/ou méthode(6RCME)", 15), (25, "Responsable pôle de sécurité ferroviaire(6RPSF)", 15), (26, "Fonctions transverses(FT)", NULL), (27, "Chargé de gestion ressource/support(4CGRS)", 26), (28, "Chargé de gestion ressources financières(4CGFI)", 26), (29, "Chargé de gestion Ressources Humaines(4CGRH)", 26), (30, "Gestionnaire ressource/support(2GERS)", 26), (31, "Gestionnaire Ressources Financières(2GERF)", 26), (32, "Gestionnaire Ressources Humaines(2GERH)", 26), (33, "Opérateur de l'environnement de travail(2OPET)", 26), (34, "Responsable de Production formation(7DUPF)", 26), (35, "Responsable ressource/support(7RRSU)", 26), (36, "Responsable ressources financières(7REFI)", 26), (37, "Responsable ressources humaines(7RERH)", 26), (38, "Spécialiste ressource/support(5SPRS)", 26), (39, "Spécialiste ressources financières(5SPFI)", 26), (40, "Spécialiste ressources humaines(5SPRH)", 26), (41, "Gestion foncière et immobilière(IM)", NULL), (42, "Manager de proximité Travaux Patrimoine(5DPXG)", 41), (43, "Opérateur/Opératrice Patrimoine(2OPGA)", 41), (44, "Responsable Affaires Immobilières(6RAFI)", 41), (45, "Responsable d'activité Patrimoine(6RAPA)", 41), (46, "Spécialiste Maintenance Immobilières Services(5SMIS)", 41), (47, "Spécialiste Méthode Patrimoine(5SMEP)", 41), (48, "Technicien(ne) Gestion Immobilière Locative(4TCIM)", 41), (49, "Technicien/Technicienne Patrimoine(4TCPA)", 41), (50, "Maintenance Ingénierie et travaux du réseau(MT)", NULL), (51, "Appui aux Projets(4APUI)", 50), (52, "Chargé de production ingénierie(5CHPI)", 50), (53, "Chef de projet MOE(6CPMO)", 50), (54, "Documentaliste(3DOCU)", 50), (55, "Expert métier Sécurité(5ESEC)", 50), (56, "Formateur/Formatrice(4FORM)", 50), (57, "Manager proximité maintenance travaux infra(5DPXV)", 50), (58, "Opérateur fabrication maintenance industrie(2OFMI)", 50), (59, "Opérateur maintenance travaux infrastructure(2OMTI)", 50), (60, "Opérateur maintenance travaux syst élec(2OMTS)", 50), (61, "Opérateur maintenance travaux telecoms(2OMTT)", 50), (62, "Référent Technique Qualité Sécurité(4RTQS)", 50), (63, "Régulateur sous stations(4RSST)", 50), (64, "Responsable Activité Maintenance Tx Infra(7RMTI)", 50), (65, "Responsable d'Equipe Maintenance et Travaux(4REMT)", 50), (66, "Responsable HQSE(5HQSE)", 50), (67, "Responsable ingénierie(7RING)", 50), (68, "Responsable MOA / Pilote d'opération(6RMOA)", 50), (69, "Responsable pôle de sécurité ferroviaire(6RPSF)", 50), (70, "Spécialiste Méthode Planif Maintenance Tx(5SMTX)", 50), (71, "Technicien M&T de l'infrastructure(4TCMT)", 50), (72, "Technicien M&T des systèmes télécoms(4TCTE)", 50), (73, "Technicien M&T systèmes électriques(4TCSE)", 50), (74, "Maintenance matériel roulant et spécialisée(MA)", NULL), (75, "Expert métier Sécurité(5ESEC)", 74), (76, "Formateur/Formatrice(4FORM)", 74), (77, "Ingénieur maintenance orga industrielle(6IMOI)", 74), (78, "Manager de proximité Matériel(5DPXM)", 74), (79, "Opérateur(rice) de maintenance industrielle(2OMIN)", 74), (80, "Opérateur(rice) maintenance matériels(2OMAT)", 74), (81, "Référent Technique Qualité Sécurité(4RTQS)", 74), (82, "Responsable Activité Maint Matériel Roulant(7RMAT)", 74), (83, "Responsable HQSE(5HQSE)", 74), (84, "Responsable pôle de sécurité ferroviaire(6RPSF)", 74), (85, "Technicien gestion maint ing orga indus(4TCOR)", 74), (86, "Technicien(ne) maintenance des Matériels(4TCMA)", 74), (87, "Médical / social(ME)", NULL), (88, "Responsable Médical/Social(6RMED)", 87), (89, "Technicien/Technicienne Paramédical(4TCME)", 87), (90, "Technicien/Technicienne social et familial(4TCSF)", 87), (91, "Pilotage et animation de sécurité et qualité(QS)", NULL), (92, "Documentaliste(3DOCU)", 91), (93, "Expert métier Sécurité(5ESEC)", 91), (94, "Formateur/Formatrice(4FORM)", 91), (95, "Référent Technique Qualité Sécurité(4RTQS)", 91), (96, "Responsable HQSE(5HQSE)", 91), (97, "Responsable pôle de sécurité ferroviaire(6RPSF)", 91), (98, "Production ferroviaire(PF)", NULL), (99, "Chef d'Escale(4CDES)", 98), (100, "Expert métier Sécurité(5ESEC)", 98), (101, "Formateur/Formatrice(4FORM)", 98), (102, "Gestionnaire moyens humains/matériels(4RESS)", 98), (103, "Manager de Proximité Fret(5DPXF)", 98), (104, "Manager de Proximité Production(5DPXP)", 98), (105, "Manutentionnaire(1MANU)", 98), (106, "Opérateur de production et de sécurité au sol(2OPSS)", 98), (107, "Opérateur ferroviaire industrie(2OFIN)", 98), (108, "Opérateur Fret au sol(2OPFR)", 98), (109, "Référent Technique Qualité Sécurité(4RTQS)", 98), (110, "Responsable conception et/ou méthode(6RCME)", 98), (111, "Responsable HQSE(5HQSE)", 98), (112, "Spécialiste gestion de production fret(6SGPF)", 98), (113, "Technicien Fret(4TFFR)", 98), (114, "Responsables / Management(MG)", NULL), (115, "Directeur commercial(8DICO)", 114), (116, "Directeur ressource/support(8DIRS)", 114), (117, "Directeur/responsable d'activité ferroviaire(8DIFE)", 114), (118, "Responsable d'unité voyageurs transverse(6RUVT)", 114), (119, "Responsable Périmètre Fret(7RFRE)", 114), (120, "Services / Relation Client / Marketing(RC)", NULL), (121, "Agent accompagnement train/relation client(2AARC)", 120), (122, "Assistant(e) commercial(le) opérationnel(le)(3ASCO)", 120), (123, "Chargé de gestion de site(2CGSI)", 120), (124, "Chargé de la relation client(2CHRC)", 120), (125, "Chargé(e) d'affaires commercial marketing(5CACM)", 120), (126, "Chef d'équipe Relation Client(4CERC)", 120), (127, "Expert métier Sécurité(5ESEC)", 120), (128, "Formateur/Formatrice(4FORM)", 120), (129, "Manager de proximité Relation client(5DPXC)", 120), (130, "Référent Technique Qualité Sécurité(4RTQS)", 120), (131, "Responsable commercial et marketing(6RCMK)", 120), (132, "Spécialiste commercial et marketing Fret(6SCMF)", 120), (133, "Technicien Commercial Fret(4TCFR)", 120), (134, "Technicien/Technicienne Commercial(e)(4TCCO)", 120), (135, "Sureté(SG)", NULL), (136, "Formateur/Formatrice(4FORM)", 135), (137, "Manager Sûreté Ferroviaire(5MGSG)", 135), (138, "Opérateur de la sûreté ferroviaire(2OPSG)", 135), (139, "Responsable Sûreté Ferroviaire(6RESG)", 135), (140, "Spécialiste Sûreté ferroviaire(5SPSG)", 135), (141, "Technicien Sûreté ferroviaire(4TSFE)", 135), (142, "Système d'information et digital(SI)", NULL), (143, "Architecte et Urbaniste des SI(6ARSI)", 142), (144, "Concepteur(rice)/Développeur(se)(4DEVL)", 142), (145, "Responsable Informatique et Digital(6RIDI)", 142), (146, "Spécialiste Informatique et Digital(5SIDI)", 142), (147, "Technicien(ne) Informatique et Digital(4TCGI)", 142);
INSERT INTO `role`
VALUES (1, 'Innovateur', 0, 0, 0, 0, 0, 0, 0, 0, 0),
    (2, 'Manager', 1, 0, 0, 0, 0, 0, 0, 0, 0),
    (3, 'Ambassadeur', 0, 1, 1, 0, 0, 0, 0, 0, 0),
    (4, 'Administrateur', 0, 0, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO `organisation`
VALUES (1, 'Ile de France'),
    (2, 'Hauts de France'),
    (3, 'Pays de la Loire'),
    (4, 'Bretagne'),
    (5, 'Normandie');
INSERT INTO `team`
VALUES (1, 'Administrateurs et ambassadeurs', 3),
    (2, 'Equipe production Ouest', 2),
    (3, 'Equipe RH', 3),
    (4, 'Equipe production télécom', 3),
    (5, 'Equipe production voie', 5);
INSERT INTO `user`
VALUES (
        1,
        'Bertrand',
        'Devantoy',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '1111',
        "Besoin de recentrer vos chakras, je maitrise l'art du feng shui. Je sais aussi animer une réunion",
        'bertrand.d@sncf.fr',
        0,
        0,
        3,
        1,
        2
    ),
    (
        2,
        'Danyel',
        'Duckman',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '2222',
        "Je maitrise la souris: clic droit, clic gauche et molette, n'hésitez pas à me demander conseil. Appelez moi pour gérer les relations avec des interlocuteurs",
        'danyel.d@sncf.fr',
        0,
        0,
        3,
        3,
        1
    ),
    (
        3,
        'Denis',
        'Perrisseau',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '3333',
        "Chercheur de nouvelles technologies, gérer la sécurité de l'information",
        'denis.p@sncf.fr',
        0,
        0,
        3,
        1,
        4
    ),
    (
        4,
        'Guillaume',
        'Peigné',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '4444',
        'Maitre des clés, gérer un budget',
        'guillaume.p@sncf.fr',
        0,
        0,
        3,
        1,
        3
    ),
    (
        5,
        'Julien',
        'Marcenac',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '5555',
        "Dresseur pokemon, gérer la sécurité de l'information",
        'julien.m@sncf.fr',
        0,
        0,
        2,
        2,
        1
    ),
    (
        6,
        'Marion ',
        'Eyraud',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '6666',
        "Gestionnaire d'une épicerie, algorithmie",
        'marion.e@sncf.fr',
        0,
        0,
        2,
        2,
        1
    ),
    (
        7,
        'Samy ',
        'Lamiri',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '7777',
        'Formateur par interim, administrer un système de base de données',
        'samy.l@sncf.fr',
        0,
        0,
        2,
        2,
        2
    ),
    (
        8,
        'Nadège',
        'Derville',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '8888',
        'Culture du houblon, connaissance juridique',
        'nadege.d@sncf.fr',
        0,
        0,
        2,
        1,
        3
    ),
    (
        9,
        'Vincent',
        'Roby',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '9999',
        "Maitrise de l'outil informatique, mangeur officiel de petit prince et de chocapic",
        'vincent.r@sncf.fr',
        0,
        0,
        3,
        4,
        2
    ),
    (
        10,
        'Nicolas',
        'Bosse',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '10101010',
        "Gérer un budget, besoin de lumière ? je suis un mordu d'electricité",
        'nicolas.b@sncf.fr',
        0,
        0,
        3,
        4,
        1
    ),
    (
        11,
        'Margaux',
        'Begard',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '11111111',
        "Gérer la sécurité de l'information, revendeur officiel des barres de céréales",
        'margaux.b@sncf.fr',
        0,
        0,
        3,
        4,
        1
    ),
    (
        12,
        'Jean Baptiste',
        'Bodin',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '12121212',
        "Algorithmique, la photographie n'a plus de secret pour moi",
        'jeanbaptiste.b@sncf.fr',
        0,
        0,
        3,
        1,
        3
    ),
    (
        13,
        'Elodie',
        'Seguin',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '13131313',
        "Animer une réunion, je suis une adepte en menuiserie",
        'elodie.s@sncf.fr',
        0,
        0,
        5,
        5,
        1
    ),
    (
        14,
        'David',
        'Le Nay',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '14141414',
        "Connaissances juridiques générales, Un pot de départ à venir ? je suis le roi de la bombarde",
        'david.l@sncf.fr',
        0,
        0,
        5,
        5,
        1
    ),
    (
        15,
        'Damien',
        'Bobon',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '15151515',
        "Administrer un système de base de données, la peinture pour moi n'a plus de secret",
        'damien.b@sncf.fr',
        0,
        0,
        5,
        5,
        2
    ),
    (
        16,
        'Alban',
        'Jaunet',
        '$argon2id$v=19$m=65536,t=5,p=1$sX/uVqDFwrNck4VjfcJ8Xw$Kzlnu428GKTiF9bm2Rt3JTo7WwyjXx8Oc7R1XIpzzsw',
        '16161616',
        'Gérer les relations avec des interlocuteurs, je suis un adepte de la plomberie',
        'alban.j@sncf.fr',
        0,
        0,
        5,
        1,
        3
    );
INSERT INTO `idea`
VALUES (
        1,
        'Voiture électrique',
        'Remplacement du parc automobile thermique par une flotte de voiture électrique',
        'Forte pollution due à l\'usage de véhicules termiques sur des trajets de moins de 10km',
        'Louer des véhicules d\'entreprise electrique et non termique',
        'Moins de pollution',
        0,
        0,
        0,
        '2023-02-02 17:16:13',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        5
    ),
    (
        2,
        'Changement ordinateur de travail',
        'Remplacer les ordinateurs actuels par des macbooks',
        'Les ordinateurs actuels sont trop bruyants, chauffent enormément et ont des problemes d\'écran',
        'Au renouvellement du matériel informatique, acheter des macbook pro de meme valeurs ',
        '+ d\'autonomie, + de légèreté, - de chauffe, - de bruit, meilleure qualitée de travail',
        0,
        0,
        0,
        '2023-02-02 17:16:13',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        3
    ),
    (
        3,
        'Enjolivement des gares',
        'Ajouter des fleurs et autres décorations pour rendre les gares plus agréables',
        'Le visuel de certaines gares ne donnent pas envie de prendre le train',
        'Installer des bacs à fleurs et des décorations pendant divers évenements',
        'Bien etre des voyageurs et des agents dans les gares',
        0,
        0,
        0,
        '2023-02-02 17:16:13',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        5
    ),
    (
        4,
        'Echange de poste',
        'Créer une plateforme pour proposer un changement de poste entre agent',
        'Monotonie et habitudes dans un poste',
        'Proposer un échange de poste de meme qualification et de meme nature',
        'S\'entendre avec un collègue pour échanger son poste et ensuite en faire part à sa hierarchie pour validation afin de gagner beaucoup de temps',
        0,
        0,
        0,
        '2023-02-02 17:16:13',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        3
    ),
    (
        5,
        'Prime exceptionnelle',
        'Offrir aux agents une prime exceptionnelle',
        'Cout de la vie augmente',
        'Offrir une prime exeptionnelle',
        'Permettre aux agents de pouvoir mettre du beurre dans les épinards',
        0,
        0,
        0,
        '2023-02-02 17:16:13',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        5
    ),
    (
        6,
        'Congé supplémentaire',
        'Ajouter un jour de congé supplémentaire',
        'Besoin de repos',
        'Offrir un jour de congé supplémentaire',
        'Permettre aux agents  de se reposer un peu',
        0,
        0,
        0,
        '2023-02-02 17:16:13',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        5
    ),
    (
        7,
        'Combattre la chaleur',
        'Fournir aux agents un moyen de raffraichissement en période estivale',
        'La chaleur dans certains postes est parfois très difficile à supporter',
        'Fournir aux agents ou installer dans les postes un ventilateur, un climatiseur ou encore une fontaine d\'eau fraiche',
        'Permettre aux agents de mieux supporter la chaleur',
        0,
        0,
        0,
        '2023-02-02 17:16:13',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        3
    ),
    (
        8,
        'Repas de noel',
        'Offrir aux agents travaillant à Noêl un repas',
        'Moral en baisse pendant les fetes',
        'Offrir un repas aux agents en poste (commandé en avance)',
        'Apporter un peu de gaité à moindre coût',
        0,
        0,
        0,
        '2023-02-02 17:16:13',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        5
    );
    